[tool.poetry]
name = "pypackage-template"
version = "0.1.0"
description = ""
authors = ["Peter Mason <pm3.141@gmail.com>"]
license = "MIT License"
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.11"
flake8-docstrings = "^1.6.0"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
flake8 = "^5.0.4"
flake8-docstrings = "^1.6.0"
isort = "^5.10.1"
pre-commit = "^2.20.0"
pytest = "^7.1.3"
pytest-mock = "^3.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 120


[tool.isort]
profile = "black"
