[tool.poetry]
name = "pypackage-template"
version = "0.1.0"
description = ""
authors = ["Peter Mason <pm3.141@gmail.com>"]
license = "MIT License"
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.11"
sphinx = "^5.3.0"
sphinx-rtd-theme = "^1.1.1"


[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
blacken-docs = "^1.12.1"
pre-commit = "^2.20.0"
pytest = "^7.1.3"
pytest-mock = "^3.10.0"
ruff = "^0.0.238"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 120


[tool.ruff]
select = ["E", "F", "C", "N", "D", "UP", "S", "B", "A", "C4", "PT", "SIM", "ARG", "PTH", "PD"]
ignore = ["D203", "D212"]
unfixable = ["B"]
line-length = 120
