minimum_pre_commit_version: 2.15.0
exclude: ^LICENSES/|\.(html|csv|svg)$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
        name: Ensure files end in newlines
      - id: trailing-whitespace
        name: Remove trailing whitespace
      - id: debug-statements
        name: Check for debug statements
      - id: check-merge-conflict
        name: Check for remaining merge conflict markers
      - id: check-toml
        name: Ensure TOML files are valid
      - id: check-yaml
        name: Ensure YAML files are valid
  - repo: https://github.com/python-poetry/poetry
    rev: 1.2.2
    hooks:
      - id: poetry-check
        name: Ensure Poetry configuration is valid
      - id: poetry-lock
        name: Ensure Poetry lock file is up to date
        args: [--check]
  - repo: https://github.com/fredrikaverpil/creosote
    rev: v2.5.0
    hooks:
      - id: creosote
        name: Identify unused dependencies with Creosote
        args:
          - --venv=$(poetry env info --path)
          - --paths={{ cookiecutter.project_slug }}
          - --deps-file=pyproject.toml
          - --sections=tool.poetry.dependencies
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        name: Ensure all imports are absolute
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        name: Check for common misspellings in text files
        types_or: [python, rst, markdown]
  - repo: https://github.com/python/black
    rev: 22.10.0
    hooks:
      - id: black
        name: Format Python code with Black
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        name: Format Python code within documentation files
        additional_dependencies: [black==22.10.0]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.238
    hooks:
      - id: ruff
        name: Lint Python code with Ruff
