minimum_pre_commit_version: 2.15.0
exclude: ^LICENSES/|\.(html|csv|svg)$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/python-poetry/poetry
    rev: 1.2.2
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/python/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.10.0]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.238
    hooks:
      - id: ruff
        args:
          [
            "select = ['E', 'F', 'C', 'N', 'D', 'UP', 'S', 'B', 'A', 'C4', 'PT', 'SIM', 'ARG', 'PTH', 'PD']",
            "unfixable = ['B']",
            "ignore = ['D203', 'D212']",
            "per-file-ignores = {'tests/*': 'S101'}",
            "line-length = 120",
          ]
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        types_or: [python, rst, markdown]
